[package]
name = "ssi-contexts"
version = "0.1.2"
authors = ["Spruce Systems, Inc."]
edition = "2018"
license = "Apache-2.0 AND W3C-20150513 AND CC-BY-SA-3.0"
license-file = "LICENSES.md"
description = "JSON-LD context files related to Verifiable Credentials, Decentralized Identifiers, and Linked Data Proofs"
repository = "https://github.com/spruceid/ssi/"
homepage = "https://github.com/spruceid/ssi/tree/main/contexts/"
documentation = "https://docs.rs/ssi-contexts/"
